accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("", views.articles, name="articles"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.article_detail, name="article_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    #
    path("index/", views.index, name="index"),
    #
    path("data-throw/", views.data_throw, name="throw"),
    path("data-catch/", views.data_catch, name="catch"),
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    path("articles/", include("articles.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        # exclude = ("created_at", "updated_at")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST, require_http_methods


@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get("next") or "index"
            return redirect(next_url)
    else:
        form = AuthenticationForm()

    context = {"form": form}
    return render(request, "accounts/login.html", context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("index")

articles/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST


def index(request):
    return render(request, "articles/index.html")


def articles(request):
    articles = Article.objects.all().order_by("-pk")
    context = {
        "articles": articles,
    }
    return render(request, "articles/articles.html", context)


def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {"article": article}
    return render(request, "articles/article_detail.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect("articles:article_detail", article.pk)
    else:
        form = ArticleForm()

    context = {"form": form}
    return render(request, "articles/create.html", context)


def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect("articles:article_detail", article.pk)
    else:
        form = ArticleForm(instance=article)

    context = {
        "form": form,
        "article": article,
    }
    return render(request, "articles/update.html", context)


@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        article.delete()
    return redirect("articles:articles")


def data_throw(request):
    return render(request, "articles/data_throw.html")


def data_catch(request):
    data = request.GET.get("message")
    context = {
        "data": data,
    }
    return render(request, "articles/data_catch.html", context)

users/views.py
from django.shortcuts import render


def users(request):
    return render(request, "users/users.html")


def profile(request, username):
    context = {
        "username": username,
    }
    return render(request, "users/profile.html", context)

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>로그인</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="로그인">
</form>

{% endblock content %}

articles/templates/articles/article_detail.html
{% extends "base.html" %}

{% block content %}

    <h2>글 상세 페이지</h2>
    <p>제목: {{ article.title }}</p>
    <p>내용: {{ article.content }}</p>
    <p>작성일시: {{ article.created_at }}</p>
    <p>수정일시: {{ article.updated_at }}</p>

    <a href="{% url 'articles:articles' %}">목록보기</a>
    <a href="{% url 'articles:update' article.pk %}">
        <button>수정하기</button>
    </a>

    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>

{% endblock content %}

articles/templates/articles/articles.html
{% extends "base.html" %}


{% block content %}
<h2>Articles</h2>

{% if request.user.is_authenticated %}
    <a href="{% url 'articles:create' %}">
        <button>새로운 글작성</button>
    </a>
{% else %}
    <a href="{% url "accounts:login" %}">로그인하고 글 작성하기</a>
{% endif %}

{% for article in articles %}
    <a href="{% url "articles:article_detail" article.pk %}">
        <p>[ {{ article.pk }} ] {{ article.title }}</p>
    </a>
{% endfor %}

{% endblock content %}

articles/templates/articles/create.html
{% extends "base.html" %}

{% block content %}
<h2>New Article</h2>

<form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">저장</button>
</form>

<a href="{% url "articles:articles" %}">목록으로</a>


{% endblock content %}

articles/templates/articles/data_catch.html
{% extends 'base.html' %}

{% block content %}
    <h1>Data Catch</h1>

    <div>
        <h2>Current Data</h2>
        <p>Current data is: {{ data }}</p>
    </div>

    <a href="{% url 'articles:throw' %}">다시 데이터 보내러가기</a>

{% endblock content %}

articles/templates/articles/data_throw.html
{% extends 'base.html' %}

{% block content %}
    <h1>Data Throw</h1>

    <form action="{% url 'articles:catch' %}" method="GET">
        <label for="message">메세지 입력</label>
        <input type="text" id="message" name="message">
        <button type="submit">전송</button>
    </form>

    <br>
    <a href="{% url 'index' %}">INDEX로 가기</a>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX PAGE</h1>

  <ul>
    <li><a href="{% url 'articles:articles' %}">글목록</a></li>
    <li><a href="{% url 'articles:throw' %}">Throw</a></li>
    <li><a href="{% url 'users:users' %}">Users</a></li>
  </ul>

{% endblock content %}

articles/templates/articles/update.html
{% extends "base.html" %}

{% block content %}
<h2>Edit Article</h2>

<form action="{% url "articles:update" article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">수정</button>
</form>

<a href="{%  article.pk %}">이전으로</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MY DJANGO</title>
</head>
<body>

    <div class="navbar">

        {% if request.user.is_authenticated %}
        <h3>Hello, {{ request.user.username }}</h3>
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="로그아웃"></input>
        </form>
        {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        {% endif %}

    </div>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
        
</body>
</html>

users/templates/users/hello.html
<h1>Users Hello</h1>

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ username }}의 프로필 페이지</h1>

    <div>
        <h2>username : {{ username }}</h2>
    </div>

    <a href="/index/">홈으로 돌아가기</a>

{% endblock content %}

users/templates/users/users.html
{% extends 'base.html' %}

{% block content %}
  <h1> Users Page </h1>

  <br>
  <a href="{% url 'index' %}">INDEX로 가기</a>
{% endblock content %}